### ISSUE TITLE
Duplicate programs in DB with same key

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#3418]
This happened in azure staging while just editing an existing program through the UI. I believe this is a real issue that could happen in prod. Since this returns a 500 error when trying to navigate to the CiviForm admin landing page, it makes it unusable. I'll look into editing the DB directly to at least restore azure staging functionality, but root cause still needs investigation.

Error from logs:

`play.api.UnexpectedException: Unexpected exception[RuntimeException: java.lang.IllegalArgumentException: Multiple entries with same key: A11y program for full audit - secondary=ProgramDefinition{id=113, adminName=A11y program for full audit - secondary, adminDescription=For accessibility full audit. To test experience with pre-filled fields, externalLink=https://www.w3.org/TR/WCAG21/, displayMode=PUBLIC, localizedName=LocalizedStrings{translations={en_US=Accessibility secondary}, isRequired=true}, localizedDescription=LocalizedStrings{translations={en_US=For accessibility full audit testing. This contains some shared questions with the primary program, so that we can test the application experience with pre-filled fields.}, isRequired=true}, blockDefinitions=[BlockDefinition{id=1, name=Personal information, description=Screen 1 description, enumeratorId=Optional.empty, visibilityPredicate=Optional.empty, optionalPredicate=Optional.empty, programQuestionDefinitions=[ProgramQuestionDefinition{id=141, programDefinitionId=Optional[113], optional=false, questionDefinition=Optional[services.question.types.NameQuestionDefinition@ac]}, ProgramQuestionDefinition{id=142, programDefinitionId=Optional[113], optional=false, questionDefinition=Optional[services.question.types.RadioButtonQuestionDefinition@ad]}, ProgramQuestionDefinition{id=143, programDefinitionId=Optional[113], optional=false, questionDefinition=Optional[services.question.types.DateQuestionDefinition@ae]}, ProgramQuestionDefinition{id=129, programDefinitionId=Optional[113], optional=false, questionDefinition=Optional[services.question.types.DropdownQuestionDefinition@a0]}, ProgramQuestionDefinition{id=150, programDefinitionId=Optional[113], optional=false, questionDefinition=Optional[services.question.types.CurrencyQuestionDefinition@b5]}]}, BlockDefinition{id=2, name=Contact information, description=Screen 2 description, enumeratorId=Optional.empty, visibilityPredicate=Optional.empty, optionalPredicate=Optional.empty, programQuestionDefinitions=[ProgramQuestionDefinition{id=144, programDefinitionId=Optional[113], optional=false, questionDefinition=Optional[services.question.types.AddressQuestionDefinition@af]}, ProgramQuestionDefinition{id=145, programDefinitionId=Optional[113], optional=false, questionDefinition=Optional[services.question.types.EmailQuestionDefinition@b0]}, ProgramQuestionDefinition{id=75, programDefinitionId=Optional[113], optional=false, questionDefinition=Optional[services.question.types.DateQuestionDefinition@6a]}]}], statusDefinitions=services.program.StatusDefinitions@28767389, createTime=Optional[2022-09-09T17:29:12.501Z], lastModifiedTime=Optional[2022-09-09T17:29:54.262Z]} and A11y program for full audit - secondary=ProgramDefinition{id=112, adminName=A11y program for full audit - secondary, adminDescription=For accessibility full audit. To test experience with pre-filled fields, externalLink=https://www.w3.org/TR/WCAG21/, displayMode=PUBLIC, localizedName=LocalizedStrings{translations={en_US=Accessibility secondary}, isRequired=true}, localizedDescription=LocalizedStrings{translations={en_US=For accessibility full audit testing. This contains some shared questions with the primary program, so that we can test the application experience with pre-filled fields.}, isRequired=true}, blockDefinitions=[BlockDefinition{id=1, name=Personal information, description=Screen 1 description, enumeratorId=Optional.empty, visibilityPredicate=Optional.empty, optionalPredicate=Optional.empty, programQuestionDefinitions=[ProgramQuestionDefinition{id=141, programDefinitionId=Optional[112], optional=false, questionDefinition=Optional[services.question.types.NameQuestionDefinition@ac]}, ProgramQuestionDefinition{id=142, programDefinitionId=Optional[112], optional=false, questionDefinition=Optional[services.question.types.RadioButtonQuestionDefinition@ad]}, ProgramQuestionDefinition{id=143, programDefinitionId=Optional[112], optional=false, questionDefinition=Optional[services.question.types.DateQuestionDefinition@ae]}, ProgramQuestionDefinition{id=129, programDefinitionId=Optional[112], optional=false, questionDefinition=Optional[services.question.types.DropdownQuestionDefinition@a0]}, ProgramQuestionDefinition{id=150, programDefinitionId=Optional[112], optional=false, questionDefinition=Optional[services.question.types.CurrencyQuestionDefinition@b5]}]}, BlockDefinition{id=2, name=Contact information, description=Screen 2 description, enumeratorId=Optional.empty, visibilityPredicate=Optional.empty, optionalPredicate=Optional.empty, programQuestionDefinitions=[ProgramQuestionDefinition{id=144, programDefinitionId=Optional[112], optional=false, questionDefinition=Optional[services.question.types.AddressQuestionDefinition@af]}, ProgramQuestionDefinition{id=145, programDefinitionId=Optional[112], optional=false, questionDefinition=Optional[services.question.types.EmailQuestionDefinition@b0]}]}], statusDefinitions=services.program.StatusDefinitions@49026687, createTime=Optional[2022-09-09T17:29:12.518Z], lastModifiedTime=Optional[2022-09-09T17:29:13.069Z]}]`

**Comment by jeanniefu** [comment]
Kind of hard to grab a stack trace from logs since it seems like each new line is its own entry in the log. It looks like it's originating from:
```
at services.program.ActiveAndDraftPrograms.buildFromCurrentVersions(ActiveAndDraftPrograms.java:35)
at services.program.ActiveAndDraftPrograms.<init>(ActiveAndDraftPrograms.java:51)
```
Code: https://github.com/civiform/civiform/blob/main/server/app/services/program/ActiveAndDraftPrograms.java#L51

**Comment by jeanniefu** [comment]
Fixed by running:
```
DELETE FROM programs WHERE id=113;
DELETE FROM version_programs WHERE programs_id=113;
```

Not sure about the root cause though.

**Comment by jeanniefu** [comment]
A related past issue: https://github.com/civiform/civiform/issues/1991
