### ISSUE TITLE
Browser tests are flaky: possible logout interaction

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#3669]
We're noticing that browser tests are a lot more flakey lately.

One hypothesis is that it's related to the new logout logic.

**Comment by shanemc-goog** [comment]
One case from a Renovate bot PR

```
Set #2. src/application_download.test.ts (27.104 s)
[40](https://github.com/civiform/civiform/actions/runs/3274716281/jobs/5388622309#step:9:41)
  ● normal application flow › all major steps
352 |     page.click('button:has-text("Sign-in"):not([disabled])'),
```

**Comment by shanemc-goog** [comment]
```
FAIL src/admin_predicates.test.ts (123.469 s)
  ● Console

    console.log
      failed to load logout page

      at src/support/index.ts:241:13
          at Generator.throw (<anonymous>)

    console.log
      failed to load logout page

      at src/support/index.ts:241:13
          at Generator.throw (<anonymous>)

  ● create and edit predicates › add a show predicate

    page.waitForURL: Timeout 5000ms exceeded.
    =========================== logs ===========================
    waiting for navigation to "**/loginForm" until "load"
    ============================================================

      246 |   // the process goes through a sequence of redirects we need to wait
      247 |   // for the final destination URL to make tests reliable.
    > 248 |   await page.waitForURL('**/loginForm')
          |              ^
      249 | }
      250 |
      251 | export const loginAsAdmin = async (page: Page) => {

      at src/support/index.ts:248:14
      at rejected (src/support/index.ts:6:65)
```
