### ISSUE TITLE
Error on document upload

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#4098]
**Describe the bug**
A resident received the below error when trying to upload additional documents for the Economic Displacement Relocation Assistance (EDRA) program in CiviForm

**To Reproduce**
_I don't know the exact steps, but this is the message that was reported:_

"Context is that the tenant had uploaded documents, was missing some additional ones, and then I requested additional documents and requested the tenant uploaded it into Civiform. This is the error they received. I’ll go ahead and move forward with the tenant’s application but wanted to ask what this error is about. "

**Screenshots**
![image](https://user-images.githubusercontent.com/86082659/214382112-4d35ec57-9d25-406a-8241-f671407326d8.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by elisekalstad** [comment]
Work around in place, resident is not blocked. P1 issue.

**Comment by gwendolyngoetz** [comment]
checkApplicantAuthorization is throwing an exception. Might be a permissions issue. Asked else for more info from the applicant.

```
[[31merror[0m] p.h.DefaultHttpErrorHandler -
! @80ceagian - Internal server error, for (GET) [/applicants/REDACTED/programs/REDACTED/review] ->
play.api.UnexpectedException: Unexpected exception[RuntimeException: java.util.NoSuchElementException: No value present]
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)
at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:246)
at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:182)
at controllers.ErrorHandler.onServerError(ErrorHandler.java:100)
at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:32)
at play.core.server.AkkaHttpServer$anonfun$2.applyOrElse(AkkaHttpServer.scala:436)
at play.core.server.AkkaHttpServer$anonfun$2.applyOrElse(AkkaHttpServer.scala:428)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
Caused by: java.lang.RuntimeException: java.util.NoSuchElementException: No value present
at controllers.applicant.ApplicantProgramReviewController.lambda$review$4(ApplicantProgramReviewController.java:91)
at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.postFire(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.NoSuchElementException: No value present
at java.base/java.util.Optional.orElseThrow(Unknown Source)
at controllers.CiviFormController.checkApplicantAuthorization(CiviFormController.java:27)
at controllers.applicant.ApplicantProgramReviewController.lambda$review$1(ApplicantProgramReviewController.java:63)
... 3 common frames omitted
```

**Comment by elisekalstad** [comment]
Sent additional applicant details via Teams for privacy. Gwen is reviewing additional information in the logs. Applicant name and log record do not align.

**Comment by msprenke** [comment]
completed with https://github.com/civiform/civiform/issues/4507
