### ISSUE TITLE
Updating Question Breaks Editing Eligibility

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#4294]
Issue #4290 was fixed, but another related issue has cropped up. Making a change to a question causes the edit eligibility screen to break.

### Repro Steps

Note that there are **two** questions being used for the eligibility configuration. 

- create questions
    - housesize: number
    - income: currency
- create program
    - add housesize
    - add income
- publish
- fill out program as applicant, success
- edit program
    - edit eligibility condition
    - check conditions
        - housesize
        - income
    - set conditions
        - housesize: number: is equal to: 1
        - income: currency: is equal to: 1
    - save conditions
- publish
- fill out program as applicant, success
- edit income question
    - set question text to income1 (any change should trigger the problem)
- edit program
    - eligibility shows correctly on the main screen
    - click edit eligibility condition
        - page loads looks correct
    - click edit existing eligibility condition
    - exception upon opening page (see below to details)

### Related:
- #4290 

### Potentially Related:
- #2047 
- #2179

### Exception:

play.api.UnexpectedException: Unexpected exception[RuntimeException: java.lang.RuntimeException: Expected a LEAF or LEAF_ADDRESS_SERVICE_AREA node but received OR node]
 at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)
 at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
 at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:246)
 at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:182)
 at controllers.ErrorHandler.onServerError(ErrorHandler.java:102)
 at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:32)
 at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:441)
 at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:433)
 at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
 at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
 at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
 at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
 at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
 at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
 at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
 at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
 at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
 at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
 at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Expected a LEAF or LEAF_ADDRESS_SERVICE_AREA node but received OR node
 at org.pac4j.play.java.SecureAction.call(SecureAction.java:79)
 at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:175)
 at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
 at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
 at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)
 at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109)
 at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)
 at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
 at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
 at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:312)
 at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:176)
 at play.api.libs.streams.Accumulator$.$anonfun$futureToSink$1(Accumulator.scala:231)
 at akka.stream.impl.Transform.apply(TraversalBuilder.scala:159)
 at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:522)
 at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:448)
 at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:440)
 at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:764)
 at play.api.libs.streams.SinkAccumulator.run(Accumulator.scala:139)
 at play.api.libs.streams.SinkAccumulator.run(Accumulator.scala:140)
 at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:428)
Caused by: java.lang.RuntimeException: Expected a LEAF or LEAF_ADDRESS_SERVICE_AREA node but received OR node
 at services.program.predicate.PredicateExpressionNode.getLeafNode(PredicateExpressionNode.java:52)
 at services.program.predicate.AutoValue_PredicateExpressionNode.getLeafNode(AutoValue_PredicateExpressionNode.java:83)
 at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
 at java.base/java.util.Collections$2.tryAdvance(Unknown Source)
 at java.base/java.util.Collections$2.forEachRemaining(Unknown Source)
 at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
 at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
 at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
 at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
 at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
 at views.admin.programs.ProgramBlockPredicateConfigureView.renderQuestionHeaders(ProgramBlockPredicateConfigureView.java:383)
 at views.admin.programs.ProgramBlockPredicateConfigureView.renderPredicateConfigurator(ProgramBlockPredicateConfigureView.java:270)
 at views.admin.programs.ProgramBlockPredicateConfigureView.render(ProgramBlockPredicateConfigureView.java:231)
 at views.admin.programs.ProgramBlockPredicateConfigureView.renderExistingEligibility(ProgramBlockPredicateConfigureView.java:157)
 at controllers.admin.AdminProgramBlockPredicatesController.configureExistingEligibilityPredicate(AdminProgramBlockPredicatesController.java:262)
 at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$107(Routes.scala:3092)
 at play.core.routing.HandlerInvokerFactory$$anon$8.resultCall(HandlerInvoker.scala:150)
 at play.core.routing.HandlerInvokerFactory$$anon$8.resultCall(HandlerInvoker.scala:149)
 at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:115)
 at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:119)

**Comment by bion** [comment]
I was able to repro the issue with the simplified steps:

1. edit an existing program to have a visibility condition that references two questions
2. publish the program
3. attempt to edit the visibility condition

**Comment by bion** [comment]
Looking at the database, the cause is that PredicateDefinitions are getting saved without a `predicateFormat` value, even though they are of type `OR_OF_SINGLE_LAYER_ANDS` and the system assumes they are of type `SINGLE_QUESTION` if the `predicateFormat` is missing
