### ISSUE TITLE
Changing Password Results in Server Error

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#4638]
**Describe the bug**

Non-Admin user changes their password. They get redirected back to CiviForm and receive an error screen. They can only get back into the system if they clear their cookies or waiting a while for the session to timeout.

```
! @818gj46ij - Internal server error, for (POST) [/callback/OidcClient] ->
play.api.UnexpectedException: Unexpected exception[IllegalArgumentException: The value must not be null or empty string]
 at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)
 at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
 at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:246)
 at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:182)
 at controllers.ErrorHandler.onServerError(ErrorHandler.java:102)
 at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:32)
 at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:441)
 at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:433)
 at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
 at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
 at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
 at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
 at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
 at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
 at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
 at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
 at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
 at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
 at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
Caused by: java.lang.IllegalArgumentException: The value must not be null or empty string
 at com.nimbusds.oauth2.sdk.id.Identifier.<init>(Identifier.java:95)
 at com.nimbusds.openid.connect.sdk.Nonce.<init>(Nonce.java:59)
 at org.pac4j.oidc.profile.creator.OidcProfileCreator.create(OidcProfileCreator.java:99)
 at auth.oidc.CiviformOidcProfileCreator.create(CiviformOidcProfileCreator.java:140)
 at auth.oidc.applicant.IdcsApplicantProfileCreator.create(IdcsApplicantProfileCreator.java:58)
 at org.pac4j.core.client.BaseClient.retrieveUserProfile(BaseClient.java:126)
 at org.pac4j.core.client.BaseClient.getUserProfile(BaseClient.java:105)
 at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:78)
 at org.pac4j.play.CallbackController.lambda$callback$0(CallbackController.java:53)
 at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
 at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)
 ... 7 common frames omitted
```

**To Reproduce**

1. Go to CiviForm Login Page
2. Click on Login, get redirected to OIDC
3. Click 'Forgot password?' and submit your username
4. If the email account for that user wait for the password reset email
5. Click the reset password button and wait to be redirected to CiviForm
6. See error

**Expected behavior**

User should not receive an error and CiviForm should successfully load after the password is changed

**Desktop (please complete the following information):**

- OS: WIndows/Mac/Linux
- Browser: Chrome
- Version: 111

**Comment by isabelcshaw** [comment]
@gwendolyngoetz have you been able to reproduce this recently? we haven't been able to

**Comment by gwendolyngoetz** [comment]
@isabelcshaw I just tried on Seattle Prod. After changing my password I get redirected to the civiform home page. The error no longer occurs, but I also was not logged in and was made a guest. Given it use to error I actually don't know if I'm supposed to be logged in or not. If someone isn't paying attention they would likely continue on as a guest.

**Comment by rockycodes** [comment]
Needs investigation by engineering to confirm if this is still an issue.
