### ISSUE TITLE
Remove Seattle IDCS Discovery URI from Config

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#4706]
Seattle deployment has already been updated.

This has a hard-coded Seattle values:
- idcs.discovery_uri

https://github.com/civiform/civiform/blob/7504861fabe6bf35d7c8bfc3d5a49ab998e20d15/server/conf/helper/auth.conf#L33

Removing the value allowed the application to remain running on localhost for development. However initial attempt of removing this prevented the server from starting in CI, thus failing the `test_prod` test which uses `prod-simulator-compose.yml`.

```
Oops, cannot start the server.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/ErrorInCustomProvider]: RuntimeException: idcs.discovery_uri must be set
  while locating IdcsClientProvider
  at modules.SecurityModule.provideClients(SecurityModule.java:257)
      \_ for 2nd parameter applicantAuthClient
  at modules.SecurityModule.provideClients(SecurityModule.java:257)
      \_ installed by: Modules$OverrideModule -> modules.SecurityModule
  at modules.SecurityModule.provideConfig(SecurityModule.java:320)
      \_ for 1st parameter clients
  at modules.SecurityModule.provideConfig(SecurityModule.java:320)
      \_ installed by: Modules$OverrideModule -> modules.SecurityModule
  at CallbackController.config(CallbackController.java:86)
      \_ for field config
  at modules.SecurityModule.configure(SecurityModule.java:77)
      \_ installed by: Modules$OverrideModule -> modules.SecurityModule
```

**Comment by gwendolyngoetz** [comment]
Closed. This is now a duplicate.
