### ISSUE TITLE
Question(s) Not Found Post Publishing

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#5278]
## Summary

> [!WARNING]
> This issue continues to crop up. It's main issue is related to edits made in multiple browser tabs as Bion detailed below.

We had a publishing issue Friday afternoon. After publishing some programs were unable to be loaded on both the admin and applicant side due to missing question IDs.

In a local backup of the I made a couple attempts (examples below) to fix the specific question, with each fix another error for a different missing question would result. Ultimately I had to just rollback the entire active version (example below) because the hydra wasn't going to be slain.

## Error From the Logs

```
[[31merror[0m] p.h.DefaultHttpErrorHandler - 
play.api.UnexpectedException: Unexpected exception[RuntimeException: java.lang.RuntimeException: Question not found for Program 1495]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)
	at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
	at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:246)
	at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:182)
	at controllers.ErrorHandler.onServerError(ErrorHandler.java:106)
	at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:32)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:441)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:433)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Question not found for Program 1495
	at controllers.applicant.ApplicantProgramReviewController.lambda$review$6(ApplicantProgramReviewController.java:163)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)
	... 7 common frames omitted
Caused by: java.lang.RuntimeException: Question not found for Program 1495
	at services.program.ProgramServiceImpl.lambda$syncProgramDefinitionQuestions$20(ProgramServiceImpl.java:1219)
	... 10 common frames omitted
Caused by: services.question.exceptions.QuestionNotFoundException: Question not found for ID: 1613
	at services.question.ReadOnlyCurrentQuestionServiceImpl.getQuestionDefinition(ReadOnlyCurrentQuestionServiceImpl.java:97)
	at services.program.ProgramServiceImpl.syncProgramQuestionDefinition(ProgramServiceImpl.java:1278)
	at services.program.ProgramServiceImpl.syncBlockDefinitionQuestions(ProgramServiceImpl.java:1265)
	at services.program.ProgramServiceImpl.syncProgramDefinitionQuestions(ProgramServiceImpl.java:1247)
	at services.program.ProgramServiceImpl.lambda$syncProgramDefinitionQuestions$20(ProgramServiceImpl.java:1216)
	... 10 common frames omitted
```

## Database Snapshot (no applicant data in here)

[db.dump.zip](https://github.com/civiform/civiform/files/12147255/db.dump.zip)

### Attempt 1

Set the program question definition json to point at the new/correct active question

```sql
update programs
set block_definitions = jsonb_set(
       block_definitions,
       '{1,questionDefinitions,0,id}',  -- Path to the field to update
       to_jsonb(1676),  -- New value to set
       false  -- If true, this will make a new key if it doesn't exist in the jsonb
   ) 
where id = 1495;
```

### Attempt 2

Update the `versions_questions` table to remove the new question and set the old question as active

```sql
delete from versions_questions where versions_id = 637 and questions_id = 1676;
insert into versions_questions (versions_id, questions_id) values (637, 1613);
```

## Actual Fix

Completely rolled back of the version

```sql
update versions set lifecycle_stage = 'active'   where id = 636 and lifecycle_stage = 'obsolete';
update versions set lifecycle_stage = 'obsolete' where id = 637 and lifecycle_stage = 'active';
update versions set lifecycle_stage = 'deleted'  where id = 640 and lifecycle_stage = 'draft';
```

**Comment by bion** [comment]
I was able to produce this error in my local dev environment with the following steps:

1. create two programs, A and B, and one question. Add the question to program A and publish all drafts.
2. remove the question from program A
3. open screen editing page for program B, open the add question sidebar, see the question
4. in a separate tab, navigate to the questions index and archive the question
5. in the tab from step 3, add the question to program B
6. publish all drafts

Result: [RuntimeException: java.util.concurrent.CompletionException: java.lang.RuntimeException: Question not found for Program 1396]

We should instead throw an exception when attempting to add a question already marked for archival to a program.

**Comment by rockycodes** [comment]
I tried the steps outlined above and the error has changed. Now on step 5, we see the following error which prevents us from adding the question to the program:

<img width="930" height="166" alt="Image" src="https://github.com/user-attachments/assets/30d1473c-976b-473c-83a6-f9189a20a77c" />

Clicking the back button brings us back to editing Program B with the questions sidebar open, but the question is no longer visible.

Still not the best user experience, but not so horrible as it was previously.
