### ISSUE TITLE
InvalidPathException Around Eligibility

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#5901]
### Details

I'm getting an exception on our staging site and reproducible on my local machine. A backup of the staging database is in the [#seattle channel on Slack](https://civiform.slack.com/archives/C035N9KCR0U/p1698800084943609). 

It appears to be throwing on [this line of the ReadOnlyApplicantProgramServiceImpl](
https://github.com/civiform/civiform/blob/71b887997c7cf0269c2453388b1dc7d0e7d38b90/server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java#L342) around Eligibility.

### Does not occur in these cases

- If you attempt to apply as a regular applicant
- If you clear the database (/dev/seed) and use the generated programs it makes

### Deployed Versions

- Staging uses the latest snapshot image
- Prod and Test are on v1.141.0 and don't appear to have the issue occur

### Repro Steps

- Run the app
- Go to dev tools -> trusted intermediary
- Scroll down to the client list and click on Applicant Dashboard for `Dino, Big`
- Click apply to the `Release testing` program
- You'll see an exception

### Exception
```
! @83d5n94aj - Internal server error, for (GET) [/applicants/2458/programs/214/review] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: com.jayway.jsonpath.InvalidPathException: Filter: [?] can not be applied to primitives. Current context is: 1696204800000]]
        at play.api.http.HttpErrorHandlerExceptions$.$anonfun$convertToPlayException$2(HttpErrorHandler.scala:381)
        at scala.Option.map(Option.scala:242)
        at play.api.http.HttpErrorHandlerExceptions$.convertToPlayException(HttpErrorHandler.scala:380)
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:373)
        at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
        at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:244)
        at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:180)
        at controllers.ErrorHandler.onServerError(ErrorHandler.java:106)
        at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:32)
        at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:441)
        at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:433)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
Caused by: java.lang.RuntimeException: com.jayway.jsonpath.InvalidPathException: Filter: [?] can not be applied to primitives. Current context is: 1696204800000
        at controllers.applicant.ApplicantProgramReviewController.lambda$review$6(ApplicantProgramReviewController.java:168)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)
        ... 7 common frames omitted
Caused by: com.jayway.jsonpath.InvalidPathException: Filter: [?] can not be applied to primitives. Current context is: 1696204800000
        at com.jayway.jsonpath.internal.path.PredicatePathToken.evaluate(PredicatePathToken.java:67)
        at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:90)
        at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:80)
        at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:90)
        at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:80)
        at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:66)
        at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:99)
        at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:107)
        at com.jayway.jsonpath.JsonPath.read(JsonPath.java:191)
        at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:88)
        at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:77)
        at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:103)
        at services.CfJsonDocumentContext.evalPredicate(CfJsonDocumentContext.java:591)
        at services.applicant.predicate.PredicateEvaluator.evaluateLeafNode(PredicateEvaluator.java:55)
        at services.applicant.predicate.PredicateEvaluator.evaluate(PredicateEvaluator.java:35)
        at services.applicant.ReadOnlyApplicantProgramServiceImpl.evaluatePredicate(ReadOnlyApplicantProgramServiceImpl.java:444)
        at services.applicant.ReadOnlyApplicantProgramServiceImpl.isBlockEligible(ReadOnlyApplicantProgramServiceImpl.java:150)
        at services.applicant.ReadOnlyApplicantProgramServiceImpl.isQuestionEligibleInBlock(ReadOnlyApplicantProgramServiceImpl.java:339)
        at services.applicant.ReadOnlyApplicantProgramServiceImpl.lambda$isApplicationNotEligible$2(ReadOnlyApplicantProgramServiceImpl.java:130)
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
```

**Comment by rockycodes** [comment]
Update: This error is happening because of a question in the program with the admin id `applicant_date_of_birth`. This is the same key used in the json blob for applicant date of birth set by a TI when they add a client. The error occurs when `applicant_date_of_birth` is used to determine eligibility because the code tries to look up `date` on `applicant_date_of_birth` as set by the TI and errors out.

Seattle has 4 programs in production that use a question with admin id `applicant_date_of_birth`. Two of these are test programs and none of them use `applicant_date_of_birth` to determine eligibility so we shouldn't see this error in prod. 

Next Steps:
@gwendolyngoetz is going to communicate the need to retire this question after these programs are done and not use `applicant_date_of_birth` as a question admin id going forward. I'm going to look into how to disallow `applicant_date_of_birth` as a question admin id programmatically.

**Comment by rockycodes** [comment]
Update: "Applicant date of birth" is one of the questions we seed when first setting up CiviForm and is intended to match the `applicant_date_of_birth` "[well known path](https://github.com/civiform/civiform/blob/46bf3b24bca316ffb87537f88fd3e9455c2abbf4/server/app/services/WellKnownPaths.java#L11)" used when a TI enters a birthday. This results in an error when a TI tries to apply to a program that contains this question, not just when there is an eligibility condition. This question is in use for many of Arkansas' programs, so we need a fix for the path and for the underlying data.

Next steps:
Do a data migration that changes all of the json blobs containing `applicant_date_of_birth` to the correct structure.
From:
```
{"applicant":{"applicant_date_of_birth":1696118400000}}
```
To:
```
{"applicant":{"applicant_date_of_birth":{"date":978307200000}}}
```

Also update the "well known path" linked above to be `applicant_date_of_birth.date`
