### ISSUE TITLE
Flaky test in staging prober tests: admin_program_list.test.ts > Program list page › program list with different active and draft image

### ISSUE THREAD

**Issue by caitlinshk** [civiform/civiform#6624]
It looks like the [`program list with different active and draft image` test](https://github.com/civiform/civiform/blob/e677def7bdcbd0da027cf93602613054f8943d79/browser-test/src/admin_program_list.test.ts#L320-L345) in `admin_program_list.test.ts` is flaky, but only in the staging prober tests and nowhere else.
 - Sample passing run: https://github.com/civiform/civiform-staging-deploy/actions/runs/7823546163/job/21344660970
 - Sample failing run: https://github.com/civiform/civiform-staging-deploy/actions/runs/7838347154/job/21389631796

Failure:
```
FAIL src/admin_program_list.test.ts (135.178 s)
  ● Program list page. › program list with different active and draft image

    page.click: Timeout 8000ms exceeded.
    Call log:
      - waiting for locator('button[form=image-file-upload-form][type="submit"]')
      -   locator resolved to <button disabled type="submit" form="image-file-upload-f…>Save image</button>
      - attempting click action
      -   waiting for element to be visible, enabled and stable
      -     element is not enabled - waiting...

      81 |   async setImageFileAndSubmit(imageFileName: string) {
      82 |     await this.setImageFile(imageFileName)
    > 83 |     await this.page.click(this.imageUploadSubmitButtonLocator)
         |                     ^
      84 |     await waitForPageJsLoad(this.page)
      85 |   }
      86 |

      at AdminProgramImage.setImageFileAndSubmit (src/support/admin_program_image.ts:83:21)
      at Object.<anonymous> (src/admin_program_list.test.ts:336:5)
```

This failure is saying that the test has uploaded an image file and now wants to click the "Submit" button to save it, but the "Submit" button is disabled so it can't click the button.

On the admin page for uploading a program image, the "Submit" buttons are disabled until the admin actually uploads a file or changes the image description. The enabling of the "Submit" buttons happens [in javascript](https://github.com/civiform/civiform/blob/e677def7bdcbd0da027cf93602613054f8943d79/server/app/assets/javascripts/admin_program_image.ts#L4), so it seems like the Javascript isn't firing for some reason. It's odd that only this test is failing because there are lots of other program image tests in `admin_program_list.test.ts` and in `admin_program_image.test.ts` that always pass in staging.

To run a test against staging, see https://github.com/civiform/civiform/wiki/Testing#running-probers-locally-against-staging.
 
In terms of debugging, the thing that I've found helpful so far is that you can have Playwright log when javascript events happen -- see https://github.com/microsoft/playwright/issues/26340. I added this code to `browser-test/src/support/admin_program_image.ts#setImageFile`:

```
if (imageFileName == 'src/assets/program-summary-image-tall.png') {
 await this.page.exposeFunction("printWhenInputChangedTall", this.printWhenInputChangedTall)
 await this.page.evaluate(`window.addEventListener('input', e => window.printWhenInputChangedTall(e))`)
} else {
 await this.page.exposeFunction("printWhenInputChanged", this.printWhenInputChanged)
 await this.page.evaluate(`window.addEventListener('input', e => window.printWhenInputChanged(e))`)
}

async printWhenInputChanged(event: InputEvent) {
  console.log('print when input changed')
}
async printWhenInputChangedTall(event: InputEvent) {
 console.log('print when input changed -- TALL')
}
```

And the log statements did appear when a file was uploaded. Unfortunately that's as far as I've gotten in the debugging process :( It seems like there's a problem loading the Javascript somehow, but I've never been able to reproduce it when directly interacting with staging. The browser tests also always pass when run locally or run via GitHub actions.

In the short term, I'm going to guard this test with `if (isLocalDevEnvironment())` so that the tests still runs locally and in GitHub actions, but not in the staging prober tests. In the long term, we'll need to debug further why this test is flaky before we can re-enable it.

**Comment by caitlinshk** [comment]
Maybe we need something like https://github.com/civiform/civiform/blob/78cc095282f6375f78de0466978047280060c989/server/app/assets/javascripts/modal.ts#L99-L100 to mark that the JS is done loading? But I don't see `loadModal` checked anywhere in the browser tests, so maybe that's a red herring.

**Comment by gwendolyngoetz** [comment]
The check on loadModal is done here

https://github.com/civiform/civiform/blob/a2ae4a36031a90cf8f86406013b1b4ed45d98d17/browser-test/src/support/wait.ts#L8-L17

**Comment by rockycodes** [comment]
Is this still an issue?

**Comment by gwendolyngoetz** [comment]
It is still guarded in the code. As to if it is still a problem I don't know.
