### ISSUE TITLE
P0 - API/JSON export Broken After Setting Question As PAI

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#7752]
Yesterday we enabled the applicant name question as a Universal name question and as PAI. That seems to have broken exporting JSON and the API.

Below stacktrace is me reproing it on my local machine. 

- Create a program
- Add a name question that is not universal and not pai
- publish
- submit an application
- Export as JSON was working
- Now set the question as universal and pai
- re-publish
- submit another application
- Export as JSON, get the exception.

Disabling the universal and pai don't appear to put it back into a working state.

```
play.api.PlayException: Execution exception[[RuntimeException: java.lang.NullPointerException: Cannot invoke "models.ApplicantModel.getFirstName()" because "this.applicant" is null]]
        at play.api.http.HttpErrorHandlerExceptions$.$anonfun$convertToPlayException$3(HttpErrorHandler.scala:407)
        at scala.Option.getOrElse(Option.scala:201)
        at play.api.http.HttpErrorHandlerExceptions$.convertToPlayException(HttpErrorHandler.scala:407)
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:390)
        at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
        at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:245)
        at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:181)
        at controllers.ErrorHandler.onServerError(ErrorHandler.java:106)
        at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:33)
        at play.core.server.AkkaHttpServer$$anonfun$invokeAction$1$1.applyOrElse(AkkaHttpServer.scala:482)
        at play.core.server.AkkaHttpServer$$anonfun$invokeAction$1$1.applyOrElse(AkkaHttpServer.scala:474)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "models.ApplicantModel.getFirstName()" because "this.applicant" is null
        at org.pac4j.play.java.SecureAction.call(SecureAction.java:79)
        at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:184)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at play.core.j.ClassLoaderExecutionContext.$anonfun$execute$1(ClassLoaderExecutionContext.scala:64)
        at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:104)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:66)
        at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
        at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
        at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:312)
        at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:176)
        at play.api.libs.streams.Accumulator$.$anonfun$futureToSink$1(Accumulator.scala:230)
        at akka.stream.impl.Transform.apply(TraversalBuilder.scala:159)
        at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:522)
        at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:448)
        at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:440)
        at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:764)
        at akka.stream.scaladsl.Source.runWith(Source.scala:118)
        at akka.stream.javadsl.Source.runWith(Source.scala:1075)
        at play.libs.streams.Accumulator$FlattenSubscriber.lambda$handler$1(Accumulator.java:285)
Caused by: java.lang.NullPointerException: Cannot invoke "models.ApplicantModel.getFirstName()" because "this.applicant" is null
        at services.applicant.ApplicantData.getApplicantFirstName(ApplicantData.java:136)
        at services.applicant.question.NameQuestion.getFirstNameValue(NameQuestion.java:71)
        at services.applicant.question.NameQuestion.getAnswerString(NameQuestion.java:124)
        at services.applicant.ReadOnlyApplicantProgramServiceImpl.addDataToBuilder(ReadOnlyApplicantProgramServiceImpl.java:337)
        at services.applicant.ReadOnlyApplicantProgramServiceImpl.getSummaryDataAllQuestions(ReadOnlyApplicantProgramServiceImpl.java:288)
        at services.export.JsonExporterService.buildApplicationExportData(JsonExporterService.java:143)
        at services.export.JsonExporterService.lambda$exportPage$1(JsonExporterService.java:96)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at services.export.JsonExporterService.exportPage(JsonExporterService.java:97)
        at services.export.JsonExporterService.export(JsonExporterService.java:75)
        at controllers.admin.AdminApplicationController.downloadAllJson(AdminApplicationController.java:160)
        at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$232(Routes.scala:4303)
        at play.core.routing.HandlerInvokerFactory$$anon$8.resultCall(HandlerInvoker.scala:160)
```

**Comment by gwendolyngoetz** [comment]
Getting a new error now.


```

play.api.PlayException: Execution exception[[RuntimeException: java.lang.NullPointerException: Cannot invoke "models.ApplicantModel.getAccount()" because "this.applicant" is null]]
        at play.api.http.HttpErrorHandlerExceptions$.$anonfun$convertToPlayException$3(HttpErrorHandler.scala:407)
        at scala.Option.getOrElse(Option.scala:201)
        at play.api.http.HttpErrorHandlerExceptions$.convertToPlayException(HttpErrorHandler.scala:407)
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:390)
        at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
        at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:245)
        at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:181)
        at controllers.ErrorHandler.onServerError(ErrorHandler.java:106)
        at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:33)
        at play.core.server.AkkaHttpServer$$anonfun$invokeAction$1$1.applyOrElse(AkkaHttpServer.scala:482)
        at play.core.server.AkkaHttpServer$$anonfun$invokeAction$1$1.applyOrElse(AkkaHttpServer.scala:474)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "models.ApplicantModel.getAccount()" because "this.applicant" is null
        at org.pac4j.play.java.SecureAction.call(SecureAction.java:79)
        at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:184)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at play.core.j.ClassLoaderExecutionContext.$anonfun$execute$1(ClassLoaderExecutionContext.scala:64)
        at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:104)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:66)
        at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
        at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
        at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:312)
        at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:176)
        at play.api.libs.streams.Accumulator$.$anonfun$futureToSink$1(Accumulator.scala:230)
        at akka.stream.impl.Transform.apply(TraversalBuilder.scala:159)
        at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:522)
        at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:448)
        at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:440)
        at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:764)
        at akka.stream.scaladsl.Source.runWith(Source.scala:118)
        at akka.stream.javadsl.Source.runWith(Source.scala:1075)
        at play.libs.streams.Accumulator$FlattenSubscriber.lambda$handler$1(Accumulator.java:285)
Caused by: java.lang.NullPointerException: Cannot invoke "models.ApplicantModel.getAccount()" because "this.applicant" is null
        at services.applicant.ApplicantData.lambda$getApplicantEmail$3(ApplicantData.java:157)
        at java.base/java.util.Optional.or(Optional.java:313)
        at services.applicant.ApplicantData.getApplicantEmail(ApplicantData.java:157)
        at services.applicant.question.EmailQuestion.getEmailValue(EmailQuestion.java:55)
        at services.applicant.question.EmailQuestion.getAnswerString(EmailQuestion.java:43)
        at services.applicant.ReadOnlyApplicantProgramServiceImpl.addDataToBuilder(ReadOnlyApplicantProgramServiceImpl.java:337)
        at services.applicant.ReadOnlyApplicantProgramServiceImpl.getSummaryDataAllQuestions(ReadOnlyApplicantProgramServiceImpl.java:288)
        at services.export.JsonExporterService.buildApplicationExportData(JsonExporterService.java:143)
        at services.export.JsonExporterService.lambda$exportPage$1(JsonExporterService.java:96)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at services.export.JsonExporterService.exportPage(JsonExporterService.java:97)
```

**Comment by gwendolyngoetz** [comment]
Phone related

```

play.api.PlayException: Execution exception[[RuntimeException: java.lang.NullPointerException: Cannot invoke "models.ApplicantModel.getCountryCode()" because the return value of "services.applicant.ApplicantData.getApplicant()" is null]]
        at play.api.http.HttpErrorHandlerExceptions$.$anonfun$convertToPlayException$3(HttpErrorHandler.scala:407)
        at scala.Option.getOrElse(Option.scala:201)
        at play.api.http.HttpErrorHandlerExceptions$.convertToPlayException(HttpErrorHandler.scala:407)
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:390)
        at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
        at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:245)
        at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:181)
        at controllers.ErrorHandler.onServerError(ErrorHandler.java:106)
        at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:33)
        at play.core.server.AkkaHttpServer$$anonfun$invokeAction$1$1.applyOrElse(AkkaHttpServer.scala:482)
        at play.core.server.AkkaHttpServer$$anonfun$invokeAction$1$1.applyOrElse(AkkaHttpServer.scala:474)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "models.ApplicantModel.getCountryCode()" because the return value of "services.applicant.ApplicantData.getApplicant()" is null
        at org.pac4j.play.java.SecureAction.call(SecureAction.java:79)
        at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:184)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at play.core.j.ClassLoaderExecutionContext.$anonfun$execute$1(ClassLoaderExecutionContext.scala:64)
        at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:104)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:66)
        at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
        at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
        at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:312)
        at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:176)
        at play.api.libs.streams.Accumulator$.$anonfun$futureToSink$1(Accumulator.scala:230)
        at akka.stream.impl.Transform.apply(TraversalBuilder.scala:159)
        at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:522)
        at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:448)
        at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:440)
        at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:764)
        at akka.stream.scaladsl.Source.runWith(Source.scala:118)
        at akka.stream.javadsl.Source.runWith(Source.scala:1075)
        at play.libs.streams.Accumulator$FlattenSubscriber.lambda$handler$1(Accumulator.java:285)
Caused by: java.lang.NullPointerException: Cannot invoke "models.ApplicantModel.getCountryCode()" because the return value of "services.applicant.ApplicantData.getApplicant()" is null
        at services.applicant.question.PhoneQuestion.getCountryCodeValue(PhoneQuestion.java:80)
        at services.applicant.question.PhoneQuestion.getAnswerString(PhoneQuestion.java:107)
        at services.applicant.ReadOnlyApplicantProgramServiceImpl.addDataToBuilder(ReadOnlyApplicantProgramServiceImpl.java:337)
        at services.applicant.ReadOnlyApplicantProgramServiceImpl.getSummaryDataAllQuestions(ReadOnlyApplicantProgramServiceImpl.java:288)
        at services.export.JsonExporterService.buildApplicationExportData(JsonExporterService.java:143)
        at services.export.JsonExporterService.lambda$exportPage$1(JsonExporterService.java:96)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at services.export.JsonExporterService.exportPage(JsonExporterService.java:97)
        at services.export.JsonExporterService.export(JsonExporterService.java:75)
        at controllers.admin.AdminApplicationController.downloadAllJson(AdminApplicationController.java:160)
        at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$232(Routes.scala:4303)
        at play.core.routing.HandlerInvokerFactory$$anon$8.resultCall(HandlerInvoker.scala:160)
        at play.core.routing.HandlerInvokerFactory$$anon$8.resultCall(HandlerInvoker.scala:159)
        at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:125)
```

**Comment by gwendolyngoetz** [comment]
Fixed. Thank you @nb1701
