### ISSUE TITLE
Blocking issue when enabling north star in deployed environment

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#8202]
**Describe the bug**
After enabling north star in a deployed environment like https://staging-aws.civiform.dev/programs, we get the following error:
<img width="809" alt="Screenshot 2024-07-29 at 7 32 07 PM" src="https://github.com/user-attachments/assets/984fa066-4cea-4e58-a437-675522cbea28">

It is impossible to navigate anywhere and this can only be fixed by navigating to /dev/feature/north_star_applicant_ui/disable, which is a workaround for disabling a feature flag. 

The errors look like this in the AWS logs:

```
play.api.UnexpectedException: Unexpected exception[RuntimeException: java.util.concurrent.CompletionException: org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "/civiform-server-0.0.1/app/views/applicant/ProgramIndexTemplate.html")] at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:384) at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala) at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:245) at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:181) at controllers.ErrorHandler.onServerError(ErrorHandler.java:106) at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:33) at play.core.server.AkkaHttpServer$$anonfun$invokeAction$1$1.applyOrElse(AkkaHttpServer.scala:488) at play.core.server.AkkaHttpServer$$anonfun$invokeAction$1$1.applyOrElse(AkkaHttpServer.scala:480) at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490) at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63) at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100) at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18) at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94) at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100) at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48) at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)

[1;31mERROR[0;39m o.t.TemplateEngine - [THYMELEAF][application-akka.actor.default-dispatcher-8] Exception processing template "applicant/ProgramIndexTemplate": An error happened during template parsing (template: "/civiform-server-0.0.1/app/views/applicant/ProgramIndexTemplate.html")
```

**To Reproduce**

1. Log in as an admin in staging 
2. Click on the settings section
3. Click to enable `NORTH_STAR_APPLICANT_UI`
4. Logout 
5. See error

**Expected behavior**
We should be able to see pages with the northstar flag turned on

**Comment by melanie-exygy** [comment]
@dkatzz @ssandbekkhaug This doesn't seem to be a problem anymore.  Can we close this issue?
