### ISSUE TITLE
API/Json Export Failing Due to Bad Configuration

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#8360]
There is a version of a program that is pointing to a bad question. This is causing the API and Json Exporting to fail.

This is causing the FreshBuck API integration to fail.

```
[1;31mERROR[0;39m o.p.p.f.SecurityFilter - Exception during authentication procedure 
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.IllegalStateException: Question type NULL_QUESTION should not be rendered. Question ID: 2597. Active program question definition is possibly pointing to an old question ID 
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) 
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) 
at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source) 
at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source) 
at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) 
at java.base/java.util.concurrent.CompletableFuture.postFire(Unknown Source) 
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) 
at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) 
at play.core.j.ClassLoaderExecutionContext.$anonfun$execute$1(ClassLoaderExecutionContext.scala:64) 
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) 
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48) 
at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) 
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) 
at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) 
at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) 
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) 
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Question type NULL_QUESTION should not be rendered. Question ID: 2597. Active program question definition is possibly pointing to an old question ID 
at controllers.api.ProgramApplicationsApiController.lambda$list$2(ProgramApplicationsApiController.java:129) 
... 14 common frames omitted 
Caused by: java.lang.IllegalStateException: Question type NULL_QUESTION should not be rendered. Question ID: 2597. Active program question definition is possibly pointing to an old question ID 
at services.applicant.question.ApplicantQuestion.getQuestion(ApplicantQuestion.java:339) 
at services.applicant.question.ApplicantQuestion.isAnswered(ApplicantQuestion.java:118) 
at services.applicant.ReadOnlyApplicantProgramServiceImpl.addDataToBuilder(ReadOnlyApplicantProgramServiceImpl.java:344) 
at services.applicant.ReadOnlyApplicantProgramServiceImpl.getSummaryDataAllQuestions(ReadOnlyApplicantProgramServiceImpl.java:300) 
at services.export.JsonExporterService.buildApplicationExportData(JsonExporterService.java:141) 
at services.export.JsonExporterService.lambda$exportPage$1(JsonExporterService.java:94) 
at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) 
at java.base/java.util.Collections$2.tryAdvance(Unknown Source) 
at java.base/java.util.Collections$2.forEachRemaining(Unknown Source) 
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) 
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) 
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) 
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) 
at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) 
at services.export.JsonExporterService.exportPage(JsonExporterService.java:95) 
at controllers.api.ProgramApplicationsApiController.lambda$list$1(ProgramApplicationsApiController.java:111) 
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) 
at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) 
at play.core.j.ClassLoaderExecutionContext.$anonfun$execute$1(ClassLoaderExecutionContext.scala:64) 
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) 
[1;31mERROR[0;39m p.h.DefaultHttpErrorHandler -   
play.api.UnexpectedException: Unexpected exception[RuntimeException: java.lang.IllegalStateException: Question type NULL_QUESTION should not be rendered. Question ID: 2597. Active program question definition is possibly pointing to an old question ID] 
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:384) 
at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala) 
at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:245) 
at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:181) 
at controllers.ErrorHandler.onServerError(ErrorHandler.java:106) 
at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:33) 
at play.core.server.AkkaHttpServer$$anonfun$invokeAction$1$1.applyOrElse(AkkaHttpServer.scala:488) 
at play.core.server.AkkaHttpServer$$anonfun$invokeAction$1$1.applyOrElse(AkkaHttpServer.scala:480) 
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490) 
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63) 
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100) 
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18) 
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94) 
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100) 
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) 
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48) 
at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) 
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) 
at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) 
at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) 
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Question type NULL_QUESTION should not be rendered. Question ID: 2597. Active program question definition is possibly pointing to an old question ID 
at controllers.api.ProgramApplicationsApiController.lambda$list$2(ProgramApplicationsApiController.java:129) 
at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source) 
at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source) 
at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) 
at java.base/java.util.concurrent.CompletableFuture.postFire(Unknown Source) 
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) 
at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) 
at play.core.j.ClassLoaderExecutionContext.$anonfun$execute$1(ClassLoaderExecutionContext.scala:64) 
... 7 common frames omitted 
Caused by: java.lang.IllegalStateException: Question type NULL_QUESTION should not be rendered. Question ID: 2597. Active program question definition is possibly pointing to an old question ID 
at services.applicant.question.ApplicantQuestion.getQuestion(ApplicantQuestion.java:339) 
at services.applicant.question.ApplicantQuestion.isAnswered(ApplicantQuestion.java:118) 
at services.applicant.ReadOnlyApplicantProgramServiceImpl.addDataToBuilder(ReadOnlyApplicantProgramServiceImpl.java:344) 
at services.applicant.ReadOnlyApplicantProgramServiceImpl.getSummaryDataAllQuestions(ReadOnlyApplicantProgramServiceImpl.java:300) 
at services.export.JsonExporterService.buildApplicationExportData(JsonExporterService.java:141) 
at services.export.JsonExporterService.lambda$exportPage$1(JsonExporterService.java:94) 
at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) 
at java.base/java.util.Collections$2.tryAdvance(Unknown Source) 
at java.base/java.util.Collections$2.forEachRemaining(Unknown Source) 
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) 
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) 
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) 
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) 
at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) 
at services.export.JsonExporterService.exportPage(JsonExporterService.java:95) 
at controllers.api.ProgramApplicationsApiController.lambda$list$1(ProgramApplicationsApiController.java:111) 
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) 
at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) 
at play.core.j.ClassLoaderExecutionContext.$anonfun$execute$1(ClassLoaderExecutionContext.scala:64) 
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) 

```

**Comment by gwendolyngoetz** [comment]
It appears the source cause was related.to caching. Restarting the application to clear that cache seems to have fixed the api.

Leaving this open for now in case I need to provide more updates.

**Comment by avaleske** [comment]
I wrote this up for Gwen on the Json API flow:
![image](https://github.com/user-attachments/assets/397fb343-e868-47cb-a48c-7fe9a297f1e4)

## API flow
1. The ProgramApplicationsApiController gets the pagination token and filters, calls into `programService.getSubmittedProgramApplicationsAllVersions()` to get a page of applications, and then passes them to `JsonExporterService.exportPage()` here:
https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/controllers/api/ProgramApplicationsApiController.java#L106-L112

2. JsonExporterService.exportPage() builds a map of all program definitions for the program, and then for each application it calls `buildApplicationExportData()` with that map an application, here:
https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/services/export/JsonExporterService.java#L89-L95

3. `buildApplicationExportData()`
- Uses a `Map<Path, AnswerData` to store the answers to export. We store an AnswerData for all paths across all versions of a program.
- First, it uses the `ReadOnlyApplicationProgramService.getSummaryDataAllQuestions()` to get `AnswerData` objects for every question in the program version associated with the application. That's here:
https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/services/export/JsonExporterService.java#L123-L131
- Then, it loops through the remaining program versions, calling `ReadOnlyApplicationProgramService.getSummaryDataAllQuestions()` for each one (with an empty `ApplicantData` so all questions are "unanswered"), and adds their `AnswerData`s to the map if the Path to that question is not already in the map. This is so that questions still show up in the API even after they're removed from a program, so API consumers don't break when a program is changed. That here:
https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/services/export/JsonExporterService.java#L133-L142
- Then the resulting map is then processed into an `ApplicationExportData` and each `AnswerData` is converted into a value to be inserted into a JSON blob, which starts here:
https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/services/export/JsonExporterService.java#L145-146

## 500 error source
There error is coming from calling [getSummaryDataAllQuestions()](https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java#L297) with the program version that had the null question:
- `getSummaryDataAllQuestions()` builds blocks for every block in the program
- Then for each block, in `[addDataToBuilder()](https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java#L332)`, it loops through every question and fetches a bunch of metadata and the scalar answers, puts them in the AnswerData, and adds it to the list that it eventually returns.

In `addDataToBuilder()`
- As it's building metadata about the question, it calls `ApplicantQuestion.isAnswered()` here:
https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java#L344-L345
- which calls `ApplicantQuestion.getQuestion()`:
https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/services/applicant/question/ApplicantQuestion.java#L117-L120
- which calls `ApplicantQuestion.getType()`, switches on the result, and throws a 500 if it's a NULL_QUESTION:
https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/services/applicant/question/ApplicantQuestion.java#L337-L343

**Comment by avaleske** [comment]
Weirdly, this issue went away after restarting the prod server, which also clears the program definition cache. It was also happening inconsistently when running from a copy of the prod DB.

Working out way back up:
- The `ApplicantQuestion` is created in `Block.getQuestions()` here:
https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/services/applicant/Block.java#L165-L177 when `getQuestions` is called from `ReadOnlyApplicantProgramServiceImpl.addDataToBuilder()`.
- The question is created from a `ProgramQuestionDefinition` that's on the Block's `BlockDefinition`.
- The `Block`s are built when `getSummaryDataAllQuestions()` calls `getBlocks()` here(ish):
https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java#L415
- That `programDefinition` is the one passes to `ApplicantService.getReadOnlyApplicantProgramService()` in `JsonExporterService` here:
https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/services/export/JsonExporterService.java#L128-L130
- Which comes from calling `programService.getAllVersionsFullProgramDefinition() here:
https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/services/export/JsonExporterService.java#L88-L90

**Comment by avaleske** [comment]
Closing as stale, since clearing the cache fixed it.

**Comment by dkatzz** [comment]
I'd be curious whether we've seen anything interesting in the logs, since we added [this](https://github.com/civiform/civiform/blob/7880dd76a7614a7dfbfd368002529307d3a74afe/server/app/repository/ProgramRepository.java#L192) in the latest version.

**Comment by gwendolyngoetz** [comment]
None at this time, but I only just updated prod a few hours ago.

**Comment by gwendolyngoetz** [comment]
The logging that was added got hit. It happened when re-publishing a program when translations were the only thing being edited. It caused an enumerator and related blocks to be removed from the program.

> [31mWARN [0;39m r.ProgramRepository - Program homewisewx with ID 2211 has the following null question ID(s): 1 in 2732 / 34 blocks, so we won't set it into the cache.

There were also dozens of this error before and after the warning message:

> [1;31mERROR[0;39m s.q.ReadOnlyVersionedQuestionServiceImpl - Question not found for ID: various ids

**Comment by avaleske** [comment]
Did clearing the cache/restarting the server fix it?

**Comment by gwendolyngoetz** [comment]
No
