### ISSUE TITLE
No CSP nonce error, after other error

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#8394]
I've seen this a few times since updating to v2.8. Only ever after some other exception occurred. Most frequently when profile merge errors.

```
java.lang.RuntimeException: No CSP nonce was generated for this request! Is CSPFilter installed and nonce enabled?
	at scala.sys.package$.error(package.scala:27)
	at views.html.helper.CSPNonce$.$anonfun$apply$1(CSPNonce.scala:26)
	at scala.Option.getOrElse(Option.scala:201)
	at views.html.helper.CSPNonce$.apply(CSPNonce.scala:26)
	at views.html.helper.CSPNonce.apply(CSPNonce.scala)
	at views.CspUtil.getNonce(CspUtil.java:11)
	at views.CspUtil.applyCsp(CspUtil.java:16)
	at views.CspUtil.lambda$applyCsp$0(CspUtil.java:21)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
	at views.CspUtil.applyCsp(CspUtil.java:21)
	at views.HtmlBundle.renderHead(HtmlBundle.java:244)
	at views.HtmlBundle.getContent(HtmlBundle.java:160)
```

**Comment by jeffpw-goog** [comment]
This error means means that we tried to add the nonce to the HTML while rendering the page, but Play hadn't set one on the request. So it looks like the filter doesn't run on the error page. @rockycodes is looking into a related issue so will work on this one as well.
