### ISSUE TITLE
Programs erroring upon submission when optional PIA question left blank

### ISSUE THREAD

**Issue by msprenke** [civiform/civiform#8834]
**Describe the bug**
We've been getting reports of errors from applicants upon submission of Guest applications.  It was determined that they were leaving the email field blank as it is an optional question on some applications due to equity reasons.

The applicant is presented with an error which makes it look like the application failed, but it does go through.  This causes frustration and duplicate entries as they attempt to reenter the application

**To Reproduce**
Create a program using a universal PIA question (phone, email, name, etc.)
Make the question optional
Start and application and leave the question blank
sumbit
error recieved

**Expected behavior**
An applicant should be able to submit an application and skip an optional PIA question without error
 following information):**

**Comment by swatkat1** [comment]
The error Logs for clarity- lay.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: java.lang.RuntimeException: java.util.NoSuchElementException: No value present]]
	at play.api.http.HttpErrorHandlerExceptions$.$anonfun$convertToPlayException$2(HttpErrorHandler.scala:400)
	at scala.Option.map(Option.scala:242)
	at play.api.http.HttpErrorHandlerExceptions$.convertToPlayException(HttpErrorHandler.scala:398)
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:390)
	at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
	at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:245)
	at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:181)
	at controllers.ErrorHandler.onServerError(ErrorHandler.java:127)
	at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:33)
	at play.core.server.AkkaHttpServer$$anonfun$invokeAction$1$1.applyOrElse(AkkaHttpServer.scala:488)
	at play.core.server.AkkaHttpServer$$anonfun$invokeAction$1$1.applyOrElse(AkkaHttpServer.scala:480)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.util.NoSuchElementException: No value present
	at controllers.applicant.ApplicantProgramReviewController.lambda$submitWithApplicantId$10(ApplicantProgramReviewController.java:279)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1163)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	... 5 common frames omitted
Caused by: java.lang.RuntimeException: java.util.NoSuchElementException: No value present
	at controllers.applicant.ApplicantProgramReviewController.lambda$submitInternal$13(ApplicantProgramReviewController.java:396)
	... 11 common frames omitted
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at services.applicant.ApplicantService.lambda$savePrimaryApplicantInfoAnswers$15(ApplicantService.java:539)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at services.applicant.ApplicantService.lambda$savePrimaryApplicantInfoAnswers$16(ApplicantService.java:512)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:423)
	at services.applicant.ApplicantService.lambda$savePrimaryApplicantInfoAnswers$17(ApplicantService.java:507)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 6 common frames omitted
